# Generated by Django 3.2.9 on 2021-11-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booxinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserved'), ('m', 'Maintenance'), ('a', 'Available'), ('o', 'On loan')], default='m', help_text='Статус книги', max_length=1),
        ),
    ]
