# Generated by Django 3.2.8 on 2021-11-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booxinstancemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('r', 'Reserved'), ('m', 'Maintenance'), ('o', 'On loan')], default='m', help_text='Статус книги', max_length=1),
        ),
    ]
