# Generated by Django 3.2.8 on 2021-11-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_booxinstancemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booxinstancemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'On loan'), ('a', 'Available'), ('m', 'Maintenance'), ('r', 'Reserved')], default='m', help_text='Статус книги', max_length=1),
        ),
    ]
