# Generated by Django 3.2.9 on 2021-11-30 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_booxinstancemodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstanceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор книги', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('o', 'On loan'), ('r', 'Reserved'), ('m', 'Maintenance'), ('a', 'Available')], default='m', help_text='Статус книги', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.bookmodel')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.DeleteModel(
            name='BooxInstanceModel',
        ),
    ]
