# Generated by Django 3.2.9 on 2022-01-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20211130_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstancemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserved'), ('m', 'Maintenance'), ('a', 'Available'), ('o', 'On loan')], default='m', help_text='Статус книги', max_length=1),
        ),
    ]
